sudo: required
services:
    - docker

before_install:
    - docker build -t udhavmore/docker-react-project -f Dockerfile.dev .

script:
    - docker run udhavmore/docker-react-project npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react-project"
    env: "docker-env"
    bucket_name: "elasticbeanstalk-us-west-2-306476627547"
    bucket_path: "docker-react-project"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "AWS_SECRET_KEY"
        